nodeLinker: node-modules

enableScripts: false

packageExtensions:
  "docusaurus-plugin-openapi-docs@*":
    peerDependencies:
      "@docusaurus/plugin-content-docs": "*"
      "@docusaurus/utils-validation": "*"
  "docusaurus-theme-openapi-docs@*":
    peerDependencies:
      "@docusaurus/theme-common": "*"
